server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1:1433;databaseName=test
    username: sa
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true